/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// KoleDaemonSetListerExpansion allows custom methods to be added to
// KoleDaemonSetLister.
type KoleDaemonSetListerExpansion interface{}

// KoleDaemonSetNamespaceListerExpansion allows custom methods to be added to
// KoleDaemonSetNamespaceLister.
type KoleDaemonSetNamespaceListerExpansion interface{}

// KoleQueryListerExpansion allows custom methods to be added to
// KoleQueryLister.
type KoleQueryListerExpansion interface{}

// KoleQueryNamespaceListerExpansion allows custom methods to be added to
// KoleQueryNamespaceLister.
type KoleQueryNamespaceListerExpansion interface{}

// SummaryListerExpansion allows custom methods to be added to
// SummaryLister.
type SummaryListerExpansion interface{}

// SummaryNamespaceListerExpansion allows custom methods to be added to
// SummaryNamespaceLister.
type SummaryNamespaceListerExpansion interface{}
