/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/openyurtio/kole/pkg/apis/lite/v1alpha1"
	scheme "github.com/openyurtio/kole/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KoleQueriesGetter has a method to return a KoleQueryInterface.
// A group's client should implement this interface.
type KoleQueriesGetter interface {
	KoleQueries(namespace string) KoleQueryInterface
}

// KoleQueryInterface has methods to work with KoleQuery resources.
type KoleQueryInterface interface {
	Create(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.CreateOptions) (*v1alpha1.KoleQuery, error)
	Update(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.UpdateOptions) (*v1alpha1.KoleQuery, error)
	UpdateStatus(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.UpdateOptions) (*v1alpha1.KoleQuery, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KoleQuery, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KoleQueryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KoleQuery, err error)
	KoleQueryExpansion
}

// koleQueries implements KoleQueryInterface
type koleQueries struct {
	client rest.Interface
	ns     string
}

// newKoleQueries returns a KoleQueries
func newKoleQueries(c *LiteV1alpha1Client, namespace string) *koleQueries {
	return &koleQueries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the koleQuery, and returns the corresponding koleQuery object, and an error if there is any.
func (c *koleQueries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KoleQuery, err error) {
	result = &v1alpha1.KoleQuery{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kolequeries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KoleQueries that match those selectors.
func (c *koleQueries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KoleQueryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KoleQueryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kolequeries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested koleQueries.
func (c *koleQueries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kolequeries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a koleQuery and creates it.  Returns the server's representation of the koleQuery, and an error, if there is any.
func (c *koleQueries) Create(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.CreateOptions) (result *v1alpha1.KoleQuery, err error) {
	result = &v1alpha1.KoleQuery{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kolequeries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(koleQuery).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a koleQuery and updates it. Returns the server's representation of the koleQuery, and an error, if there is any.
func (c *koleQueries) Update(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.UpdateOptions) (result *v1alpha1.KoleQuery, err error) {
	result = &v1alpha1.KoleQuery{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kolequeries").
		Name(koleQuery.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(koleQuery).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *koleQueries) UpdateStatus(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.UpdateOptions) (result *v1alpha1.KoleQuery, err error) {
	result = &v1alpha1.KoleQuery{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kolequeries").
		Name(koleQuery.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(koleQuery).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the koleQuery and deletes it. Returns an error if one occurs.
func (c *koleQueries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kolequeries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *koleQueries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kolequeries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched koleQuery.
func (c *koleQueries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KoleQuery, err error) {
	result = &v1alpha1.KoleQuery{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kolequeries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
