/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/kole/pkg/apis/lite/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInfEdgeNodes implements InfEdgeNodeInterface
type FakeInfEdgeNodes struct {
	Fake *FakeLiteV1alpha1
	ns   string
}

var infedgenodesResource = schema.GroupVersionResource{Group: "lite.openyurt.io", Version: "v1alpha1", Resource: "infedgenodes"}

var infedgenodesKind = schema.GroupVersionKind{Group: "lite.openyurt.io", Version: "v1alpha1", Kind: "InfEdgeNode"}

// Get takes name of the infEdgeNode, and returns the corresponding infEdgeNode object, and an error if there is any.
func (c *FakeInfEdgeNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InfEdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(infedgenodesResource, c.ns, name), &v1alpha1.InfEdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InfEdgeNode), err
}

// List takes label and field selectors, and returns the list of InfEdgeNodes that match those selectors.
func (c *FakeInfEdgeNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InfEdgeNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(infedgenodesResource, infedgenodesKind, c.ns, opts), &v1alpha1.InfEdgeNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InfEdgeNodeList{ListMeta: obj.(*v1alpha1.InfEdgeNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.InfEdgeNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested infEdgeNodes.
func (c *FakeInfEdgeNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(infedgenodesResource, c.ns, opts))

}

// Create takes the representation of a infEdgeNode and creates it.  Returns the server's representation of the infEdgeNode, and an error, if there is any.
func (c *FakeInfEdgeNodes) Create(ctx context.Context, infEdgeNode *v1alpha1.InfEdgeNode, opts v1.CreateOptions) (result *v1alpha1.InfEdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(infedgenodesResource, c.ns, infEdgeNode), &v1alpha1.InfEdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InfEdgeNode), err
}

// Update takes the representation of a infEdgeNode and updates it. Returns the server's representation of the infEdgeNode, and an error, if there is any.
func (c *FakeInfEdgeNodes) Update(ctx context.Context, infEdgeNode *v1alpha1.InfEdgeNode, opts v1.UpdateOptions) (result *v1alpha1.InfEdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(infedgenodesResource, c.ns, infEdgeNode), &v1alpha1.InfEdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InfEdgeNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInfEdgeNodes) UpdateStatus(ctx context.Context, infEdgeNode *v1alpha1.InfEdgeNode, opts v1.UpdateOptions) (*v1alpha1.InfEdgeNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(infedgenodesResource, "status", c.ns, infEdgeNode), &v1alpha1.InfEdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InfEdgeNode), err
}

// Delete takes name of the infEdgeNode and deletes it. Returns an error if one occurs.
func (c *FakeInfEdgeNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(infedgenodesResource, c.ns, name), &v1alpha1.InfEdgeNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInfEdgeNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(infedgenodesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InfEdgeNodeList{})
	return err
}

// Patch applies the patch and returns the patched infEdgeNode.
func (c *FakeInfEdgeNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InfEdgeNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(infedgenodesResource, c.ns, name, pt, data, subresources...), &v1alpha1.InfEdgeNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InfEdgeNode), err
}
