/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/kole/pkg/apis/lite/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKoleDaemonSets implements KoleDaemonSetInterface
type FakeKoleDaemonSets struct {
	Fake *FakeLiteV1alpha1
	ns   string
}

var koledaemonsetsResource = schema.GroupVersionResource{Group: "lite.openyurt.io", Version: "v1alpha1", Resource: "koledaemonsets"}

var koledaemonsetsKind = schema.GroupVersionKind{Group: "lite.openyurt.io", Version: "v1alpha1", Kind: "KoleDaemonSet"}

// Get takes name of the koleDaemonSet, and returns the corresponding koleDaemonSet object, and an error if there is any.
func (c *FakeKoleDaemonSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KoleDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(koledaemonsetsResource, c.ns, name), &v1alpha1.KoleDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleDaemonSet), err
}

// List takes label and field selectors, and returns the list of KoleDaemonSets that match those selectors.
func (c *FakeKoleDaemonSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KoleDaemonSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(koledaemonsetsResource, koledaemonsetsKind, c.ns, opts), &v1alpha1.KoleDaemonSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KoleDaemonSetList{ListMeta: obj.(*v1alpha1.KoleDaemonSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.KoleDaemonSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested koleDaemonSets.
func (c *FakeKoleDaemonSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(koledaemonsetsResource, c.ns, opts))

}

// Create takes the representation of a koleDaemonSet and creates it.  Returns the server's representation of the koleDaemonSet, and an error, if there is any.
func (c *FakeKoleDaemonSets) Create(ctx context.Context, koleDaemonSet *v1alpha1.KoleDaemonSet, opts v1.CreateOptions) (result *v1alpha1.KoleDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(koledaemonsetsResource, c.ns, koleDaemonSet), &v1alpha1.KoleDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleDaemonSet), err
}

// Update takes the representation of a koleDaemonSet and updates it. Returns the server's representation of the koleDaemonSet, and an error, if there is any.
func (c *FakeKoleDaemonSets) Update(ctx context.Context, koleDaemonSet *v1alpha1.KoleDaemonSet, opts v1.UpdateOptions) (result *v1alpha1.KoleDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(koledaemonsetsResource, c.ns, koleDaemonSet), &v1alpha1.KoleDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleDaemonSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKoleDaemonSets) UpdateStatus(ctx context.Context, koleDaemonSet *v1alpha1.KoleDaemonSet, opts v1.UpdateOptions) (*v1alpha1.KoleDaemonSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(koledaemonsetsResource, "status", c.ns, koleDaemonSet), &v1alpha1.KoleDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleDaemonSet), err
}

// Delete takes name of the koleDaemonSet and deletes it. Returns an error if one occurs.
func (c *FakeKoleDaemonSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(koledaemonsetsResource, c.ns, name), &v1alpha1.KoleDaemonSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKoleDaemonSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(koledaemonsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KoleDaemonSetList{})
	return err
}

// Patch applies the patch and returns the patched koleDaemonSet.
func (c *FakeKoleDaemonSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KoleDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(koledaemonsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.KoleDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleDaemonSet), err
}
