/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/kole/pkg/apis/lite/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKoleQueries implements KoleQueryInterface
type FakeKoleQueries struct {
	Fake *FakeLiteV1alpha1
	ns   string
}

var kolequeriesResource = schema.GroupVersionResource{Group: "lite.openyurt.io", Version: "v1alpha1", Resource: "kolequeries"}

var kolequeriesKind = schema.GroupVersionKind{Group: "lite.openyurt.io", Version: "v1alpha1", Kind: "KoleQuery"}

// Get takes name of the koleQuery, and returns the corresponding koleQuery object, and an error if there is any.
func (c *FakeKoleQueries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KoleQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kolequeriesResource, c.ns, name), &v1alpha1.KoleQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleQuery), err
}

// List takes label and field selectors, and returns the list of KoleQueries that match those selectors.
func (c *FakeKoleQueries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KoleQueryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kolequeriesResource, kolequeriesKind, c.ns, opts), &v1alpha1.KoleQueryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KoleQueryList{ListMeta: obj.(*v1alpha1.KoleQueryList).ListMeta}
	for _, item := range obj.(*v1alpha1.KoleQueryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested koleQueries.
func (c *FakeKoleQueries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kolequeriesResource, c.ns, opts))

}

// Create takes the representation of a koleQuery and creates it.  Returns the server's representation of the koleQuery, and an error, if there is any.
func (c *FakeKoleQueries) Create(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.CreateOptions) (result *v1alpha1.KoleQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kolequeriesResource, c.ns, koleQuery), &v1alpha1.KoleQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleQuery), err
}

// Update takes the representation of a koleQuery and updates it. Returns the server's representation of the koleQuery, and an error, if there is any.
func (c *FakeKoleQueries) Update(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.UpdateOptions) (result *v1alpha1.KoleQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kolequeriesResource, c.ns, koleQuery), &v1alpha1.KoleQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleQuery), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKoleQueries) UpdateStatus(ctx context.Context, koleQuery *v1alpha1.KoleQuery, opts v1.UpdateOptions) (*v1alpha1.KoleQuery, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kolequeriesResource, "status", c.ns, koleQuery), &v1alpha1.KoleQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleQuery), err
}

// Delete takes name of the koleQuery and deletes it. Returns an error if one occurs.
func (c *FakeKoleQueries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kolequeriesResource, c.ns, name), &v1alpha1.KoleQuery{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKoleQueries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kolequeriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KoleQueryList{})
	return err
}

// Patch applies the patch and returns the patched koleQuery.
func (c *FakeKoleQueries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KoleQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kolequeriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KoleQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KoleQuery), err
}
