/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/kole/pkg/apis/lite/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQueryNodes implements QueryNodeInterface
type FakeQueryNodes struct {
	Fake *FakeLiteV1alpha1
	ns   string
}

var querynodesResource = schema.GroupVersionResource{Group: "lite.openyurt.io", Version: "v1alpha1", Resource: "querynodes"}

var querynodesKind = schema.GroupVersionKind{Group: "lite.openyurt.io", Version: "v1alpha1", Kind: "QueryNode"}

// Get takes name of the queryNode, and returns the corresponding queryNode object, and an error if there is any.
func (c *FakeQueryNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.QueryNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(querynodesResource, c.ns, name), &v1alpha1.QueryNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueryNode), err
}

// List takes label and field selectors, and returns the list of QueryNodes that match those selectors.
func (c *FakeQueryNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QueryNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(querynodesResource, querynodesKind, c.ns, opts), &v1alpha1.QueryNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.QueryNodeList{ListMeta: obj.(*v1alpha1.QueryNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.QueryNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested queryNodes.
func (c *FakeQueryNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(querynodesResource, c.ns, opts))

}

// Create takes the representation of a queryNode and creates it.  Returns the server's representation of the queryNode, and an error, if there is any.
func (c *FakeQueryNodes) Create(ctx context.Context, queryNode *v1alpha1.QueryNode, opts v1.CreateOptions) (result *v1alpha1.QueryNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(querynodesResource, c.ns, queryNode), &v1alpha1.QueryNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueryNode), err
}

// Update takes the representation of a queryNode and updates it. Returns the server's representation of the queryNode, and an error, if there is any.
func (c *FakeQueryNodes) Update(ctx context.Context, queryNode *v1alpha1.QueryNode, opts v1.UpdateOptions) (result *v1alpha1.QueryNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(querynodesResource, c.ns, queryNode), &v1alpha1.QueryNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueryNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQueryNodes) UpdateStatus(ctx context.Context, queryNode *v1alpha1.QueryNode, opts v1.UpdateOptions) (*v1alpha1.QueryNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(querynodesResource, "status", c.ns, queryNode), &v1alpha1.QueryNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueryNode), err
}

// Delete takes name of the queryNode and deletes it. Returns an error if one occurs.
func (c *FakeQueryNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(querynodesResource, c.ns, name), &v1alpha1.QueryNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQueryNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(querynodesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.QueryNodeList{})
	return err
}

// Patch applies the patch and returns the patched queryNode.
func (c *FakeQueryNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.QueryNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(querynodesResource, c.ns, name, pt, data, subresources...), &v1alpha1.QueryNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueryNode), err
}
