/*
Copyright 2022 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	litev1alpha1 "github.com/openyurtio/kole/pkg/apis/lite/v1alpha1"
	versioned "github.com/openyurtio/kole/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openyurtio/kole/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openyurtio/kole/pkg/client/listers/lite/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KoleDaemonSetInformer provides access to a shared informer and lister for
// KoleDaemonSets.
type KoleDaemonSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KoleDaemonSetLister
}

type koleDaemonSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKoleDaemonSetInformer constructs a new informer for KoleDaemonSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKoleDaemonSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKoleDaemonSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKoleDaemonSetInformer constructs a new informer for KoleDaemonSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKoleDaemonSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LiteV1alpha1().KoleDaemonSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LiteV1alpha1().KoleDaemonSets(namespace).Watch(context.TODO(), options)
			},
		},
		&litev1alpha1.KoleDaemonSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *koleDaemonSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKoleDaemonSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *koleDaemonSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&litev1alpha1.KoleDaemonSet{}, f.defaultInformer)
}

func (f *koleDaemonSetInformer) Lister() v1alpha1.KoleDaemonSetLister {
	return v1alpha1.NewKoleDaemonSetLister(f.Informer().GetIndexer())
}
