name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GOPATH: /tmp/

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Generate 
      run: make generate
    - name: Fmt 
      run: make fmt
    - name: Vet 
      run: make vet 
    - name: Build 
      run: make 
